### Get access token

POST {{TOKEN_URL}}
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id={{CLIENT_ID}}&client_secret={{CLIENT_SECRET}}&username={{USER_NAME}}&password={{USER_PASSWORD}}&scope={{CLIENT_SCOPE}}

> {%
    client.global.set("JWT", response.body.access_token);
%}